# Generated by Django 5.0.4 on 2024-04-30 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrandView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThingsSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_publication', models.DateTimeField(verbose_name='date publications')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('Trainig_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('summary_training', models.CharField(max_length=255, verbose_name='Краткое Содержания')),
                ('full_training', models.TextField(blank=True, verbose_name='full text')),
                ('links_training', models.URLField(blank=True, verbose_name='URL')),
                ('video_training', models.FileField(blank=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео')),
                ('graphic_illustrations', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иллюстрация’, upload_to = main/')),
            ],
            options={
                'verbose_name': 'Обучение',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='TEXT')),
                ('publication_date', models.DateField(verbose_name='DATE')),
            ],
        ),
    ]
